### ISSUE TITLE
HI，我看到你研究了 PPTX 文件的解析，请教下你最后选用了什么方案？

### ISSUE THREAD

**Issue by zbysir** [s10y10/self-test#1]
我看你研究了使用下面的库来解析 PPTX：
- https://github.com/djwxfdt/ppt-parse
- https://github.com/g21589/PPTX2HTML
- https://github.com/meshesha/PPTXjs

想问下你的场景以及最后怎么解决的？我有个需求也是需要解析 PPTX，但开源的项目我找了一圈（上面的）都不是很完善易用。

**Comment by s10y10** [comment]
我当时是做一个在线的类似PPT的项目，要添加导入PPT的功能，需要把PPT的数据结构解析转换成自己项目的数据结构，当时也没有找到特别合适的开源方案，最后是把 https://github.com/djwxfdt/ppt-parse 这个仓库的源码拉下来，根据实际情况再进行修改的

**Comment by zbysir** [comment]
@s10y10 感谢，我也是做和你们一样的产品，也正在使用 https://github.com/djwxfdt/ppt-parse  这个库来改，甚至在线 PPT 也借鉴的另一个开源项目：https://github.com/pipipi-pikachu/PPTist，现在最大的问题就是他两的数据结构不一致，得一一转换并且补齐 ppt-parse 库不支持的如 图表 等功能，有点费时间。最后问句你的项目可以有偿提供帮助不？QQ 1019654929

**Comment by s10y10** [comment]
@zbysir 已经是好几年前在之前公司做的项目了，现在估计也帮不上啥忙了，就祝好运吧...

**Comment by zbysir** [comment]
@s10y10 哈哈，好的，多谢

**Comment by zbysir** [comment]
<img width="1857" alt="image" src="https://github.com/s10y10/self-test/assets/61535029/eec79eb9-60c9-45c9-a24f-15674a79dc23">
😢
